namespace: dev

dbt:
  # Deployment configuration
  deployment:
    name: dbt
    replicas: 1
    strategy:
      type: RollingUpdate
      maxSurge: 3
    image: 
      repository: slowsunday/dbt-service
      tag: latest
    ports:
      port: 8000

    securityContext:
      runAsUser: 1000
      privileged: false
      runAsNonRoot: false

    livenessProbe:
      enabled: true
      exec:
        command:
          - ./readinessProbe.sh
      initialDelaySeconds: 10
      periodSeconds: 360
      timeoutSeconds: 5

    readinessProbe:
      enabled: true
      exec:
        command:
          - ./readinessProbe.sh
      initialDelaySeconds: 10
      timeoutSeconds: 5
    
  # ConfigMap configuration
  configmap:
    enabled: true
    name: dbt-config
    svcHost: clickhouse

  # Service configuration
  service:
    type: ClusterIP
    ports:
      http:
        name: http
        port: 8000
        targetPort: 8000
